# Generated by Django 4.1.7 on 2023-03-09 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
